sudo: false

language: node_js

node_js:
  - '6'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run dev
  - npm run test-ci

after_script:
  - sh ./build/print_logs.sh

addons:
  sauce_connect: true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "fae-builds"
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: dist
    upload_dir: nightly/$TRAVIS_COMMIT
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "fae-builds"
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: dist
    upload_dir: nightly/HEAD
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "fae-builds"
    skip_cleanup: true
    acl: public_read
    region: us-west-2
    local_dir: dist
    upload-dir: release/$TRAVIS_TAG
    on:
      tags: true

env:
  global:
    - SAUCE_USERNAME=faejs
    - secure: "Zt8SsozLoD3Jss0r7bOb6a5/q1/oiJh/95NtPEjfHiMrxOsEgFrn8Vr8i7iVJnhOsc2UMzuC5j7zKBepkvTkle4uyCBMlcVl98C/aBoXKZ2rZ8VX+rVqncVSJIF7lMKd5gmgL5X3XJK73rSniqdZZy60b91qB7vtMjVAilG1aHk1DCbsGS8vtup12KUG4WpU0uX4K8s0mh7tlGdHqw8PMqjUs8LzP37V5auBBgbeH7w1mmm0Qv8KXep+5ErRzg9FjrBZnDl6lFrfXeKI44qgQWn2aO0x6iREaHM6ppnA7oeJB54EZiBs0C2JjMA0r37jFfXuy9Ofx4KfkxAnGQs9ohAECTinDu87Y3znY4YqmOmjn6Nn6ayYqvmwTC3CuzhUUtLS7nxSL65/F/7xWubj7dMSsfQFb83aYHhy3xue2NBRGOXsRdlMxz+nis0mO4XWcAAYlryu2/hoL8gkMna3vKWxcBLkpjaZjTbOy0zqpE2sodGSdXxv3AwVII/eHXE8sbNlcrGl4lPkWbLa3PUikPuBAETlwhM1fll0epK74qbwF3z7dn/ESqNBjiWCcBr0JaY1bYCENxnCR3uWIA7e8J5t1W6DWM719IzXDWLzBV4egxN4IgDwSEiCv9O/J2qdYjQ8YQSvVUC48hLjGYVTyTELxeIX8Jj3tkspy45fNSQ="
    - secure: "aTgQWMjQvOO5ppXcdeUgve33l07dykPKXBNf8KLM4hJshUONsVGdeIa5jRet/w6qA1/Q1v3OLp96Hle85PQZcGcjUUt/oijKRUAjyd1HJ7uvGMW5O2w1nuwtRyIwEXlIFSNld79Fmz9WpRYr4x5h2+UnSJl4peSnJ/1Ex16aIQrczfDjoehgzV43GL5Fa1tZiUS3VQ1YbM8pZCCY515uyagwrlKvBDGTX18iTtel0I4ZdZXEhtriLcojmAG3Gcg1paxgNP2F1FMIMOXEDbmnEVi0SAhdgD9xWkVCWfspSyxyFuPJITg8F9Ua1EKdgDPc0bAT6+hKvlm7h0o5fHR5NV5cwE30xWqoLptytpakCOGy9cv/EK3/jj7oWbcFl5PPWXyfdFtMY2ZDAlZl08hhIPHX0JBC8uRy8u4OgbhosFixPDT/Ap1jvJFt7kC6pmD6BW9nCF62qmt0IdEQhj7XQS9UK2rEAKvcOts3S5cmiCA0xy1VPXfVl8EfGFhSI8ywu5W2GUxMy/qh9gjExZcGsCJnrmzquuHecoT7z2hZgh2QVat/oJcPfFWUMOjf/fHN+FsVdELjiZbyNm2cQD4W6DeT5RRQkyMu2fd6jYlz4/2HMC5V00nYCcqDVn8TmoqVLQCnqxcx7c/mgeLG5KeIuzZDR6aAGvbXZ3x/I6nyLdM="
    - secure: "wxq07p4X9B4+eWwFObIcevZLh79PkwHvUS9oFJDKdCZZqssWpS+2gfhWmLC+Lpr/R8qjScxzBoiqJWrn/E+nyoqSkllc9k/LYFZc4Z0P+1NSjLl32RdBLltPucqC7Rgr5DlUAvRvBlJY1jvKFaYW5BRaQ1ItozEbmOE5s8xiz3gmm9b493zFGCr4sdtrgjaB8LatWrYtyQLxJvtnfSnZnXfdZkOQssRCoAffk2gXb43TEZIuxBHMTOPS+Ia/XQWDvJNuniZD1EtQMgOAzhLM5JYnQHq4jU2Cyq79hLAC/7AZ1w++TM5pljHFP0jfbOuKk9IMBBGGrFd/3Ep8A/O3ZDJpuXnG8ltTYId5OYfQ32Xl2yN2BH5w1PiQw7lefdNDuqIBNs9t8o8OVfq9BjgQcDtwMinct9Osm6+ZWsiaVPyaaPmaeK9T3S3aWeE+I6UwHaFsKPJW95QnrdGR2FgJ4slAKWza9B0PqMj9eip7uManectZ/dFmCmWWuJwinXROG65dKoZyRvy+XGzIMqXO0o8iO9nW+9GXR2fd3wOW/cIdaFCvJfQuFpKcF2CaI0mWPEUAcLIJlvn4mJpJHSm4wtjWBPhIG9858IwnAfJbYVr+77Sv5SyT1TwKNtkj/GTZrMlAU47ldDls+WSqfy2H9k//vYguk8yu2EPk0+IUrPg="
