sudo: false

language: node_js

node_js:
  - '6'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install

script:
  - npm test

after_script:
  - sh ./build/print_logs.sh

addons:
  sauce_connect: true

env:
  global:
    - LOGS_DIR=.
    - SAUCE_USERNAME=englercj
    - secure: "baoRWqWe7ou5t/texf7c1M86iU9aw1kuyJC/5LXdkGk2jflDrZpTFqDJUI34FT5UkPO2eHXcrNtc7eZV10pDXTfWjtadCxpjyQWTjXIYchltpKSW345x9ZAB7KTUjlruMXKPbBsUAQm6ClJq3arOaWr+1ycO2gsoA1q1Ttt+vPrRQoioS88x1tmcvW3jRZBTIfGFpHV6FhlPgW1oecs5E/6v53muxuWkxjiMEmbW84gNvr68O7e2+LEoPBp88O8mJQkJSf3PBvaBGcfinZeVjmIGSle3iqmQpGlvA1dChPWK/7eAPYZ/LQJUfbj9VwtsbZHcjacnqGtvvPDGf2k/kg3QpVfAJELLokBaYnuL1rI2X++WYHcc1qLaYQ0WuYE4Cpj6gIkmiEjfMl3sQfmVTWeVtPmVpe5tj4bOb5zHdFR3g+3i7kCVyEDtAWzEV16Vx6NhIEBOMg/hhB9apRRLAmo1vmQfr7+Qf2WdzJS0V8jLN6AAuAiqFi28Agu2fNc1vwD2LnJh7qGDS9l7oYEs3X3HfRh6JdWbsam2O7BxRYZOr0fJkQcX80Bboz4PfnWC8354eipykY3X9vBb7dZCCEJ0uHkfz6ZWqwXgHynqfwIXtsf7elB72tAafcdOl6jtPnVlkLN0VAqYQPodG++AbaqZKZJZ9TTxhpZ+4BG8dc0="

# notifications:
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/d2120f3f2bb39a4531b2
#     on_success: always  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: always    # default: false
