sudo: false

language: node_js

node_js:
  - '6'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install

script:
  - npm test

after_script:
  - sh ./build/print_logs.sh

addons:
  sauce_connect: true

env:
  global:
    - SAUCE_USERNAME=englercj
    - secure: "baoRWqWe7ou5t/texf7c1M86iU9aw1kuyJC/5LXdkGk2jflDrZpTFqDJUI34FT5UkPO2eHXcrNtc7eZV10pDXTfWjtadCxpjyQWTjXIYchltpKSW345x9ZAB7KTUjlruMXKPbBsUAQm6ClJq3arOaWr+1ycO2gsoA1q1Ttt+vPrRQoioS88x1tmcvW3jRZBTIfGFpHV6FhlPgW1oecs5E/6v53muxuWkxjiMEmbW84gNvr68O7e2+LEoPBp88O8mJQkJSf3PBvaBGcfinZeVjmIGSle3iqmQpGlvA1dChPWK/7eAPYZ/LQJUfbj9VwtsbZHcjacnqGtvvPDGf2k/kg3QpVfAJELLokBaYnuL1rI2X++WYHcc1qLaYQ0WuYE4Cpj6gIkmiEjfMl3sQfmVTWeVtPmVpe5tj4bOb5zHdFR3g+3i7kCVyEDtAWzEV16Vx6NhIEBOMg/hhB9apRRLAmo1vmQfr7+Qf2WdzJS0V8jLN6AAuAiqFi28Agu2fNc1vwD2LnJh7qGDS9l7oYEs3X3HfRh6JdWbsam2O7BxRYZOr0fJkQcX80Bboz4PfnWC8354eipykY3X9vBb7dZCCEJ0uHkfz6ZWqwXgHynqfwIXtsf7elB72tAafcdOl6jtPnVlkLN0VAqYQPodG++AbaqZKZJZ9TTxhpZ+4BG8dc0="

notifications:
  slack:
    secure: sABvUPIGxfKaUc6sE7DMFY+qE4a2RWYaOQPnHk6AOtG+rAGs2JT2poKnWasXSQ+HzemVCDtqVNY7U1o24X9norXq1CZpgsKLzumRzaH3c3Xwg6F26t8996ThSAIxTy4pJas1+LdjmebDcUulmIb0S2ffpzatgqjWd41vdeNeQWAKF9M84I8RsTpqx5TDgXLvajyKtElXUOE58wmEOW4e97AuKj0YEHRoEaFFUSyb2l58+uvG4Eg5ScWj9NmIzsp5SvTORsevev4zqv7pmQPn5vKnoDK8FA3DF977DJgz8Fk4coJCP2bACvx38OHXg1JPwpyXXlVH8B9m6FpX3CO3TOaZ8qBBvsaaBYggBdqVe+uuzRiS13Vhb9H8tkyOx7l4NjaJkvonRvh/3ugMgIUEjNlxPaQb5UTdHFw4LIB419nwPv79+o7Dzw/74hsXTBVdIIUyXIU0oi4PnAt6w0ulAAWtEMhzx3ZMtITv7SS6wyc4CQ+v9dcdqDrh2+TqKx1ABZc74nqd8kOh9dYmfgU7o9Sd8H3EzSAnZ33kC7Crsdz3EJ180LnOHwueDv+owYiJNQzoTBUva4KV2PUzeUVu7xUywyWpisqeolpGilmij0zQPXjgmwpE3n+03zgzCu8pltFwNaNAujqUKBygcJZHm4rEUr5PhaWJk2Lk2EsvC30=
